# -*- coding: utf-8 -*-
"""lista de exercicios

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K9VXO9hPnD4X_ftEFStTR_lEI84A9QJY

# Listas

<span style="color: red;"><b>Todos os exercícios são feitos partindo-se do pressuposto de que todas as entradas são dadas de forma correta. Casos limite não mencionados no enunciado não são abordados porque não fazem parte do exercício.</b></span>

#### 1. Faça um Programa que leia as vendas dos vendedores, mostre a venda de cada vendedor com o seu nome e a média de vendas.
"""

vendas = [1000, 1500, 1200, 1300]
vendedores = ["Fulano", "Beltrano", "Ciclano", "Lira"]

cont = 0

while cont < 4:
  print("Vendedor: {} - Vendas: {}".format(vendedores[cont], vendas[cont]))
  cont += 1

print("\nA média das Vendas é R$ {}".format(sum(vendas) / 4))

"""#### 2. Faça um Programa que crie uma lista com as médias de cada aluno, imprima as médias de cada aluno e a quantidade de alunos com média maior que 7."""

alunos = ["José", "Joana", "Maria", "Carla", "Mauricio", "Andre", "Tiago", "Enzo", "Amanda", "Alessandra"]
notas = [
    [10, 9, 8, 8],
    [9, 7, 6, 4],
    [10, 10, 10, 10],
    [5, 3, 10, 9],
    [7, 6, 6, 6],
    [7, 7, 8, 7],
    [7, 7, 7, 9],
    [8, 5, 6, 7],
    [10, 9, 7, 4],
    [10, 1, 3, 3],
]

cont = 0
totalAlunos = 0

while cont < 10:
  print("Aluno: {} - Média: {}".format(alunos[cont], sum(notas[cont]) / 4))
  if sum(notas[cont]) / 4 > 7:
    totalAlunos += 1
  cont += 1

print("\nTotal de Alunos com média maior que 7: {}".format(totalAlunos))

"""#### 3. Foram anotadas as idades e salários de 30 funcionários. Faça um programa que determine quantos funcionários com mais de 25 anos possuem salário inferior à média de todos os salários."""

idades = [35,32,50,33,48,50,33,48,22,49,35,38,20,47,49,48,34,21,48,44,48,30,25,42,42,23,25,23,38,35]
salarios = [3739,2219,3554,3978,4014,3270,4792,3879,2981,2384,4826,2460,3680,4318,1872,1770,4640,3929,3295,1729,3965,4267,4007,1916,2987,2943,3852,4543,2055,1730]

mediaTotal = sum(salarios) / 30
salarioInf = 0
funcionario = 0

while funcionario < 30:
  if idades[funcionario] > 25 and salarios[funcionario] < mediaTotal:
    salarioInf += 1
  funcionario += 1

print("A quantidade de funcionarios que possuem mais de 25 anos e recebem abaixo da média é de {} pessoas".format(salarioInf))

"""#### 4.Em quais meses a média de temperatura foi maior do que a média nacional?"""

meses = [
    'Janeiro',
    'Fevereiro',
    'Março',
    'Abril',
    'Maio',
    'Junho',
    'Julho',
    'Agosto',
    'Setembro',
    'Outubro',
    'Novembro',
    'Dezembro'
]

temperaturas = [30, 29, 28, 28, 25, 26, 20, 21, 19, 25, 27, 32]

mediaTotal = sum(temperaturas) / 12
tempMes = 0

while tempMes < 12:
  if temperaturas[tempMes] > mediaTotal:
    print("A temperatura de {} foi de {} ºC e ultrapassou a média de {} ºC".format(meses[tempMes], temperaturas[tempMes], mediaTotal))
  tempMes += 1

"""#### 5. As Organizações Tabajara resolveram dar um abono aos seus colaboradores em reconhecimento ao bom resultado alcançado durante o ano que passou. Para isto contratou você para desenvolver a aplicação que servirá como uma projeção de quanto será gasto com o pagamento deste abono.
<pre>Após reuniões envolvendo a diretoria executiva, a diretoria financeira e os representantes do sindicato laboral, chegou-se a seguinte forma de cálculo:
. Cada funcionário receberá o equivalente a 20% do seu salário bruto de dezembro;
. O piso do abono será de 100 reais, isto é, aqueles funcionários cujo salário for muito baixo, recebem este valor mínimo;

Neste momento, não se deve ter nenhuma preocupação com colaboradores com tempo menor de casa, descontos, impostos ou outras particularidades. O programa deverá calcular o valor do abono concedido a cada colaborador, de acordo com a regra definida acima. Ao final, o programa deverá apresentar:</pre>
<pre>
O salário de cada funcionário, juntamente com o valor do abono;
O número total de funcionário processados;
O valor total a ser gasto com o pagamento do abono;
O número de funcionário que receberá o valor mínimo de 100 reais;
O maior valor pago como abono; A tela abaixo é um exemplo de execução do programa, apenas para fins ilustrativos.
<pre>
Projeção de Gastos com Abono
============================

Salário: 1000
Salário: 300
Salário: 500
Salário: 100
Salário: 4500
Salário: 0

Salário    - Abono     
R$ 1000.00 - R$  200.00
R$  300.00 - R$  100.00
R$  500.00 - R$  100.00
R$  100.00 - R$  100.00
R$ 4500.00 - R$  900.00

Foram processados 5 colaboradores
Total gasto com abonos: R$ 1400.00
Valor mínimo pago a 3 colaboradores
Maior valor de abono pago: R$ 900.00
"""

lista_salarios = [1000, 300, 500, 200, 1500, 3000, 3400, 5000, 7000, 2000, 600, 800, 250, 1500, 20000]
abonos = []

cont = 0
valorMinimo = 0
valorMaior = 0

while cont < len(lista_salarios):
  if lista_salarios[cont] < 1000:
    abonos.append(100)
    valorMinimo +=1
  else:
    valorAbono = (lista_salarios[cont] * 20) / 100
    abonos.append(valorAbono)
    if valorAbono >  valorMaior:
      valorMaior = valorAbono

  cont += 1

print("Salario & Abono\n")
cont = 0
while cont < len(lista_salarios):
  print("Salário: {} - Abono: {}".format(lista_salarios[cont], abonos[cont]))
  cont += 1

print("\nInformações")
print("Total de funcionarios processados: {}".format(len(lista_salarios)))
print("Total gasto com Abono: R$ {}".format(sum(abonos)))
print("O Valor mínimo foi pago para {} funcionarios".format(valorMinimo))
print("O Valor mais alto para um abono foi de R$ {}".format(valorMaior))

"""#### 6. Faça um programa que carregue uma lista com os modelos de cinco carros (exemplo de modelos: FUSCA, GOL, VECTRA etc). Carregue uma outra lista com o consumo desses carros, isto é, quantos quilômetros cada um desses carros faz com um litro de combustível. Calcule e mostre:
<pre>
a. O modelo do carro mais econômico;
b. Quantos litros de combustível cada um dos carros cadastrados consome para percorrer uma distância de 1000 quilômetros e quanto isto custará, considerando um que a gasolina custe R$ 2,25 o litro. Abaixo segue uma tela de exemplo. O disposição das informações deve ser o mais próxima possível ao exemplo. Os dados são fictícios e podem mudar a cada execução do programa.</pre>
```
Comparativo de Consumo de Combustível

Veículo 1
Nome: fusca
Km por litro: 7
Veículo 2
Nome: gol
Km por litro: 10
Veículo 3
Nome: uno
Km por litro: 12.5
Veículo 4
Nome: Vectra
Km por litro: 9
Veículo 5
Nome: Peugeout
Km por litro: 14.5

Relatório Final
 1 - fusca           -    7.0 -  142.9 litros - R$ 321.43
 2 - gol             -   10.0 -  100.0 litros - R$ 225.00
 3 - uno             -   12.5 -   80.0 litros - R$ 180.00
 4 - vectra          -    9.0 -  111.1 litros - R$ 250.00
 5 - peugeout        -   14.5 -   69.0 litros - R$ 155.17
O menor consumo é do peugeout.
```
"""

print('Comparativo de Consumo de Combustível')
veiculos = ['fusca','gol', 'uno', 'vectra', 'peugeot']
autonomias = [7, 10, 12.5, 9, 14.5]

cont = 0
while cont < len(veiculos):
  print("\nVeiculo {}\nModelo: {}\nConsumo: {} Km por litro".format(cont + 1, veiculos[cont], autonomias[cont]))
  cont += 1

print('Relatório Final\n')

cont = 0
menorConsumo = 0
while cont < len(veiculos):
  print("{} - {} | {} Km por Litro | {} Litros | R$ {}".format(cont + 1, veiculos[cont], autonomias[cont], 1000 / autonomias[cont], (1000 / autonomias[cont]) * 2.25))
  if autonomias[cont] > menorConsumo:
    menorConsumo = autonomias[cont]
  cont += 1

print("\nO Veiculo com menor consumo é o {}".format(veiculos[autonomias.index(menorConsumo)]))

"""#### 7. Uma empresa paga seus vendedores com base em comissões. O vendedor recebe \\$200 por semana mais 9 por cento de suas vendas brutas daquela semana. Por exemplo, um vendedor que teve vendas brutas de \\$3000 em uma semana recebe \\$200 mais 9 por cento de \\$3000, ou seja, um total de \\$470. Escreva um programa (usando um array de contadores) que determine quantos vendedores receberam salários nos seguintes intervalos de valores:
<pre>
$200 - $299
$300 - $399
$400 - $499
$500 - $599
$600 - $699
$700 - $799
$800 - $899
$900 - $999
$1000 em diante
</pre>

Existem várias formas de fazer. Faça primeiro da forma que parecer mais intuitiva para você.

Em seguida, caso queira um desafio:
Desafio: Crie uma forma para chegar na posição da lista a partir do salário, sem fazer vários ifs aninhados.
"""

vendas = [1000, 2000, 3000, 4000, 5000, 6000, 5500, 4500, 3600]

cont = 0
classe1, classe2, classe3, classe4, classe5, classe6, classe7, classe8, classe9, classe10 = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
while cont < len(vendas):
  valor = 200 + ((vendas[cont] * 9) / 100)

  if valor > 200 and valor < 300:
    classe1 += 1
  elif valor >= 300 and valor < 400:
    classe2 += 1
  elif valor >= 400 and valor < 500:
    classe3 += 1
  elif valor >= 500 and valor < 600:
    classe4 += 1
  elif valor >= 600 and valor < 700:
    classe5 += 1
  elif valor >= 700 and valor < 800:
    classe6 += 1
  elif valor >= 800 and valor < 900:
    classe7 += 1
  elif valor >= 900 and valor < 1000:
    classe8 += 1
  elif valor >= 1000:
    classe9 += 1

print("{} funcionarios recebem entre R$ 200 e R$ 299".format(classe1))
print("{} funcionarios recebem entre R$ 300 e R$ 399".format(classe2))
print("{} funcionarios recebem entre R$ 400 e R$ 499".format(classe3))
print("{} funcionarios recebem entre R$ 500 e R$ 599".format(classe4))
print("{} funcionarios recebem entre R$ 600 e R$ 699".format(classe5))
print("{} funcionarios recebem entre R$ 700 e R$ 799".format(classe6))
print("{} funcionarios recebem entre R$ 800 e R$ 899".format(classe7))
print("{} funcionarios recebem entre R$ 900 e R$ 999".format(classe8))
print("{} funcionarios recebem acima de R$ 1000".format(classe9))