# -*- coding: utf-8 -*-
"""lista de exercicios-01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10g782V3coDE63fI1FWUZk6q1JLwLpSKz

# Estruturas de decisão

<span style="color: red;"><b>Todos os exercícios são feitos partindo-se do pressuposto de que todas as entradas são dadas de forma correta. Casos limite não mencionados no enunciado não são abordados porque não fazem parte do exercício.</b></span>

#### 1. Faça um Programa que peça dois números e imprima o maior deles.
"""

n1 = int(input("Digite um número: "))
n2 = int(input("Digite outro número: "))

if n1 > n2 :
  print("O maior valor digitado foi: {}".format(n1))

else:
  print("O maior número digitado foi {}".format(n2))

"""#### 2. Faça um Programa que peça um valor e mostre na tela se o valor é positivo ou negativo."""

valor = int(input("Escolha um número: "))

if valor >= 0 :
  print("O número {} é positivo".format(valor))

else:
  print("O número {} é negativo".format(valor))

"""#### 3. Faça um Programa que verifique o estado civil de uma pessoa. Se a letra digitada é "C" (Casado), "S" (Solteiro), "D" (Divorciado), "V" (Viúvo) ou "O" (outros). Conforme a letra escrita pelo usuário seu programa deve escrever o estado civil, exemplo:

Usuário digita: C

Seu programa deve responder:
C - Casado
"""

situacao = str(input("Digite a letra do seu estado civil: "))
letra = situacao.upper()

if letra == "C" :
  print("Sua situação é C - Casado")

elif letra == "S" :
  print("Sua situação é S - Solteiro")

elif letra == "D" :
  print("Sua situação é D - Divorciado")

elif letra == "V" :
  print("Sua situação é V - Viuvo")

elif letra == "O" :
  print("Sua situação é O - Outros")

else:
  print("Estado civil invalido, escolha uma das opções a seguir: C, S, D, V, O.")

"""#### 4. Faça um Programa que verifique se o e-mail digitado faz parte dos e-mails de spam."""

emails_spam = "fulano@gmail.com,beltrano@gmail.com,ciclano@gmail.com"

email = str(input("Digite seu email: "))

if emails_spam.find(email) >= 0:
  print("Seu email faz parte do spam")

else:
  print("Seu email está ok e não faz parte do Spam")

"""#### 5. Faça um programa para a leitura de duas notas parciais de um aluno. O programa deve calcular a média alcançada por aluno e apresentar:

##### A mensagem "Aprovado", se a média alcançada for maior ou igual a sete;
##### A mensagem "Reprovado", se a média for menor do que sete;
##### A mensagem "Aprovado com Distinção", se a média for igual a dez.
"""

digitar = "sim"
nota = 0
contador = 0

while digitar == "sim":
  n1 = float(input("Qual a nota do aluno? "))
  nota = nota + n1
  contador = contador + 1
  digitar = str(input("Você deseja digitar outra nota? sim ou não? "))

print("A média final do Aluno é {}".format(nota / contador))

"""#### 6. Faça um Programa que leia o orçamento de 3 empresas e mostre o maior deles."""

orc1 = float(input("Digite o primeiro orçamento: "))
orc2 = float(input("DIgite o segundo orçamento: "))
orc3 = float(input("Digite o terceiro orçamento: "))

if orc1 > orc2 and orc1 > orc3:
  print("Entre os orçamentos o primeiro é o maior deles! R$ {}".format(orc1))

elif orc2 > orc1 and orc2 > orc3:
  print("Entre os orçamentos o segundo é o maior deles! R$ {}".format(orc2))

elif orc3 > orc2 and orc3 > orc1:
  print("Entre os orçamentos o terceiro é o maior deles! R$ {}".format(orc3))

"""#### 7. Faça um Programa que leia três orçamentos e mostre o maior e o menor deles."""

orc1 = float(input("Digite o primeiro orçamento: "))
orc2 = float(input("DIgite o segundo orçamento: "))
orc3 = float(input("Digite o terceiro orçamento: "))

if orc1 > orc2 and orc1 > orc3:
  print("Entre os orçamentos o primeiro é o maior deles! R$ {}".format(orc1))
  if orc2 < orc3:
    print("E o menor dos orçamentos foi o segundo! {}".format(orc2))
  else:
    print("E o menor dos orçamentos foi o terceiro! {}".format(orc3))

elif orc2 > orc1 and orc2 > orc3:
  print("Entre os orçamentos o segundo é o maior deles! R$ {}".format(orc2))
  if orc1 < orc3:
    print("E o menor dos orçamentos foi o primeiro! {}".format(orc1))
  else:
    print("E o menor dos orçamentos foi o terceiro! {}".format(orc3))

elif orc3 > orc2 and orc3 > orc1:
  print("Entre os orçamentos o terceiro é o maior deles! R$ {}".format(orc3))
  if orc1 < orc2:
    print("E o menor dos orçamentos foi o primeiro! {}".format(orc1))
  else:
    print("E o menor dos orçamentos foi o segundo! {}".format(orc2))

"""#### 8. Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato."""

print("Informe abaixo o preço dos três produtos a serem analisados")
p1 = float(input("Digite o preço do Produto 1: "))
p2 = float(input("Digite o preço para o Produto 2: "))
p3 = float(input("Digite o preço do produto 3: "))

if p1 < p2 and p1 < p3:
  print("A melhor opção para você é o Produto 1 - R$ {}".format(p1))

elif p2 < p1 and p2 < p3:
  print("A melhor opção para você é o Produto 2 - R$ {}".format(p2))

elif p3 < p1 and p3 < p2:
  print("A melhor opção para você é o Produto 3 - R$ {}".format(p3))

"""#### 9. Faça um Programa que leia três números e mostre-os em ordem decrescente."""

n1 = float(input("Digite o primeiro número: "))
n2 = float(input("Digite o segundo número: "))
n3 = float(input("Digite o terceiro número: "))

if n1 < n2 and n1 < n3:
  if n2 < n3:
    print("Os números digitados em ordem crescente é {}, {}, {}".format(n1, n2, n3))
  else:
    print("Os números digitados em ordem crescente é {}, {}, {}".format(n1, n3, n2))

elif n2 < n1 and n2 < n3:
  if n1 < n3:
    print("Os números digitados em ordem crescente é {}, {}, {}".format(n2, n1, n3))
  else:
    print("Os números digitados em ordem crescente é {}, {}, {}".format(n2, n3, n1))

else:
  if n1 < n2:
    print("Os números digitados em ordem crescente é {}, {}, {}".format(n3, n1, n2))
  else:
    print("Os números digitados em ordem crescente é {}, {}, {}".format(n3, n2, n1))

"""#### 10. Faça um Programa que pergunte em que turno você estuda. Peça para digitar M-matutino ou V-Vespertino ou N- Noturno. Imprima a mensagem "Bom Dia!", "Boa Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso."""

mensagem = str(input("Olá, em qual turno você estuda? "))
turno = mensagem.upper()

if turno == 'M':
  print("Tenha um Bom dia!")

elif turno == 'V':
  print("Tenha uma Boa tarde!")

elif turno == 'N':
  print("Tenha uma Boa noite!")

else:
  print("Turno incorreto! Por favor, escolha entre os turnos: M, V, N")

"""#### 11. As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contraram para desenvolver o programa que calculará os reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:

##### salários até R\\$ 280,00 (incluindo) : aumento de 20%

##### salários entre R\\$ 280,00 e R\\$ 700,00 : aumento de 15%

##### salários entre R\\$ 700,00 e R\\$ 1500,00 : aumento de 10%

##### salários de R\\$ 1500,00 em diante : aumento de 5% Após o aumento ser realizado, informe na tela:

###### o salário antes do reajuste;

###### o percentual de aumento aplicado;

###### o valor do aumento;

###### o novo salário, após o aumento.

###### Obs: Não vamos nos preocupar tanto com a formatação dos números (nº de casas decimais, por exemplo, veremos isso no próximo módulo)
"""

valor = float(input("Olá, digite aqui o salário atual do colaborador: "))

if valor <= 280:
  salario = valor + ((valor * 20) / 100)
  print("\nSalario antes do reajuste: {}\nPercentual de aumento: 20%\nValor do aumento: {}\nNovo salario: {}".format(valor, salario - valor, salario))

elif valor > 280 and valor <= 700:
  salario = valor + ((valor * 15) / 100)
  print("\nSalario antes do reajuste: {}\nPercentual de aumento: 15%\nValor do aumento: {}\nNovo salario: {}".format(valor, salario - valor, salario))

elif valor > 700 and valor <= 1500:
  salario = valor + ((valor * 10) / 100)
  print("\nSalario antes do reajuste: {}\nPercentual de aumento: 10%\nValor do aumento: {}\nNovo salario: {}".format(valor, salario - valor, salario))

elif valor > 1500:
  salario = valor + ((valor * 5) / 100)
  print("\nSalario antes do reajuste: {}\nPercentual de aumento: 5%\nValor do aumento: {}\nNovo salario: {}".format(valor, salario - valor, salario))

"""#### 12 . Faça um programa para o cálculo de uma folha de pagamento, sabendo que os descontos são do Imposto de Renda, que depende do salário bruto (conforme tabela abaixo) e que o FGTS corresponde a 11% do Salário Bruto, mas não é descontado (é a empresa que deposita). O Salário Líquido corresponde ao Salário Bruto menos os descontos. O programa deverá pedir ao usuário o valor da sua hora e a quantidade de horas trabalhadas no mês.

Desconto do IR:<br>
Salário Bruto até 900 (inclusive) - isento<br>
Salário Bruto até 1500 (inclusive) - desconto de 5%<br>
Salário Bruto até 2500 (inclusive) - desconto de 10%<br>
Salário Bruto acima de 2500 - desconto de 20%<br>
Imprima na tela as informações, dispostas conforme o exemplo abaixo. No exemplo o valor da hora é 5 e a quantidade de hora é 220.

Salário Bruto: (5 * 220)        : R\\$ 1100,00<br>
(-) IR (5%)                     : R\\$   55,00<br>
(-) INSS ( 10%)                 : R\\$  110,00<br>
FGTS (11%)                      : R\\$  121,00<br>
Total de descontos              : R\\$  165,00<br>
Salário Liquido                 : R\\$  935,00<br>

###### Obs: Não vamos nos preocupar tanto com a formatação dos números (nº de casas decimais, por exemplo, veremos isso no próximo módulo)
"""

print("Olá, para fazermos o seu calculo primeiro preciso de algumas informações")
valor = float(input("Qual o valor da sua hora trabalhada? "))
horas = int(input("Quantas horas foram trabalhadas no mês? "))

salario = horas * valor

#calculo do IR

ir = 0

if salario > 900 and salario <= 1500:
  ir = 5

elif salario > 1500 and salario <= 2500:
  ir = 10

elif salario > 2500:
  ir = 20

inss = (salario * 10) / 100
fgts = (salario * 11) / 100

#verificação do salario
if salario <= 900:
  print("\nSalário bruto:({} * {}) R$ {}\n(-) IR(Isento):\n(-) INSS(10%): R$ {}\nFGTS(11%): R$ {}\nTotal de descontos: R$ {}\nSalário liquido: R$ {}".format(horas, valor, salario, inss, fgts, inss + ir, salario - (inss + ((salario * ir) / 100))))

else:
  print("\nSalário bruto:({} * {}) R$ {}\n(-) IR({}): {} \n(-) INSS(10%): R$ {}\nFGTS(11%): R$ {}\nTotal de descontos: R$ {}\nSalário liquido: R$ {}".format(horas, valor, salario,ir, (salario * ir) / 100, inss, fgts, inss + ((salario * ir) / 100), salario - (inss + ((salario * ir) / 100))))

"""#### 13. Faça um Programa que leia um número e exiba o dia correspondente da semana. (1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido."""

dia = int(input("Digite o número do dia: "))

if dia == 1:
  print("Dia 1 - Domingo")

elif dia == 2:
  print("Dia 2 - Segunda")

elif dia == 3:
  print("Dia 3 - Terça")

elif dia == 4:
  print("Dia 4 - Quarta")

elif dia == 5:
  print("Dia 5 - Quinta")

elif dia == 6:
  print("Dia 6 - Sexta")

elif dia == 7:
  print("Dia 7 - Sabado")

else:
  print("Número incorreto, escolha entre 1 e 7")

"""#### 14. Faça um programa que lê as duas notas parciais obtidas por um aluno numa disciplina ao longo de um semestre, e calcule a sua média. Em seguida, mostre qual conceito o aluno teve. A atribuição de conceitos obedece à tabela abaixo:
<pre>
Média de Aproveitamento  Conceito
Entre 9.0 e 10.0        A
Entre 7.5 e 9.0         B
Entre 6.0 e 7.5         C
Entre 4.0 e 6.0         D
Entre 4.0 e zero        E
</pre>
"""

n1 = float(input("Digite a primeira nota: "))
n2 = float(input("Digite a segunda nota: "))
media = (n1 + n2) / 2

if media > 9 and media <= 10:
  print("Nota média: {}\nConceito: A".format(media))

elif media > 7.5 and media <= 9:
  print("Nota média: {}\nConceito: B".format(media))

elif media > 6 and media <= 7.5:
  print("Nota média: {}\nConceito: C".format(media))

elif media > 4 and media <= 6:
  print("Nota média: {}\nConceito: D".format(media))

elif media >= 0 and media <= 4:
  print("Nota média: {}\nConceito: E".format(media))

else:
  print("\nA média das notas não pode ser menor que Zero ou maior que Dez!!")

"""#### 15. Você está construindo um calendário para controlar dias de trabalho a pedido do RH. Nessa construção, você vai precisar definir quais anos são bissextos e quais não são, para montar o calendário de forma correta. Faça um Programa que peça um número correspondente a um determinado ano e em seguida informe se este ano é ou não bissexto.
<pre>
Dica para determinar se um ano é bissexto:
- São bissextos todos os anos múltiplos de 400, p.ex.: 1600, 2000, 2400, 2800...
- São bissextos todos os múltiplos de 4, exceto se for múltiplo de 100 mas não de 400,
p.ex.: 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024, 2028...
- Não são bissextos todos os demais anos.<br>
ex1: 2004 é múltiplo de 4, mas não é múltiplo de 100, então é bissexto.
ex2: 2000 é múltiplo de 4, mas é múltiplo de 100, só que também é multiplo de 400, então é bissexto (porque todo ano múltiplo de 400 é bissexto, independente do resto).
ex3: 1900 é múltiplo de 4, é múltiplo de 100, mas não é múltiplo de 400, então não é bissexto

</pre>

Dica: lembre que: numero % 4 é o resto da divisão do número por 4, ex: 10 % 3 = 1 (já que 10/3 = 3 e resta 1)
"""

ano = int(input("Qual o ano desejado: "))

if (ano%4==0 and ano%100!=0) or (ano%400==0):
  print("O ano de {} é Bissexto!".format(ano))
else:
  print("O ano de {} é não é Bissexto!".format(ano))

"""#### 16. Faça um Programa para leitura de três notas parciais de um aluno. O programa deve calcular a média alcançada por aluno e presentar:
<pre>
A mensagem "Aprovado", se a média for maior ou igual a 7, com a respectiva média alcançada;
A mensagem "Reprovado", se a média for menor do que 7, com a respectiva média alcançada;
A mensagem "Aprovado com Distinção", se a média for igual a 10.
</pre>
"""

n1 = float(input("Digite a primeira nota: "))
n2 = float(input("Digite a segunda nota: "))
n3 = float(input("Digite a terceira nota: "))

media = (n1 + n2 + n3) / 3

if media >= 7 and media < 10:
  print("Aluno aprovado, nota média: {}".format(media))

elif media > 0 and media < 7:
  print("Aluno reprovado, nota média: {}".format(media))

elif media == 10:
  print("Aluno aprovado com Distinção, nota média: 10")

else:
  print("A nota média não pode ser menor que Zero ou maior que Dez")

"""#### 17. João Papo-de-Pescador, homem de bem, comprou um microcomputador para controlar o rendimento diário de seu trabalho. Toda vez que ele traz um peso de peixes maior que o estabelecido pelo regulamento de pesca do estado de São Paulo (50 quilos) deve pagar uma multa de R$ 4,00 por quilo excedente. João precisa que você faça um programa que leia a variável peso (peso de peixes) e calcule o excesso. Gravar na variável excesso a quantidade de quilos além do limite e na variável multa o valor da multa que João deverá pagar. Imprima os dados do programa com as mensagens adequadas."""

peso = float(input("Qual a quantidade de peixes pescados? "))

if peso > 50:
  excesso = peso - 50
  multa = excesso * 4
  print("Quantidade de peixes pescados: {} Kg\nPeso em excesso: {} Kg\nValor da multa a ser paga: R$ {}".format(peso, excesso, multa))

elif peso > 0 and peso <= 50:
  print("A quantidade de peixe pescado não é passiva de multa")

else:
  print("A Quantidade informada não pode ser igual ou menor a Zero")

"""#### 18. Faça um Programa para um caixa eletrônico. O programa deverá perguntar ao usuário a valor do saque e depois informar quantas notas de cada valor serão fornecidas. As notas disponíveis serão as de 1, 5, 10, 50 e 100 reais. O valor mínimo é de 10 reais e o máximo de 600 reais. O programa não deve se preocupar com a quantidade de notas existentes na máquina.
<pre>
Exemplo 1: Para sacar a quantia de 256 reais, o programa fornece duas notas de 100, uma nota de 50, uma nota de 5 e uma nota de 1;
Exemplo 2: Para sacar a quantia de 399 reais, o programa fornece três notas de 100, uma nota de 50, quatro notas de 10, uma nota de 5 e quatro notas de 1.
</pre>

Dica1: numero // 10 vai te dar como resposta a parte inteira da divisão do número por 10.<br>
Dica2: numero % 10 vai te dar o resto da divisão do número por 10.
"""

numero = int(input('Valor para sacar [10-600]: '))

cem = int(numero / 100)
numero = numero % 100

cinquenta = int(numero/50)
numero = numero % 50

dez = int(numero/10)
numero = numero % 10

cinco = int(numero/5)
numero = numero % 5

um = numero

print("\nNotas a serem sacadas:")
if cem != 0: print('{} notas R$100,00'.format(cem))
if cinquenta != 0: print('{} notas R$ 50,00'.format(cinquenta))
if dez != 0: print('{} notas R$ 10,00'.format(dez))
if cinco != 0: print('{} notas R$ 5,00'.format(cinco))
if um != 0: print('{} notas R$ 1,00'.format(um))

"""#### 19. Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:
<pre>
"Telefonou para a vítima?"
"Esteve no local do crime?"
"Mora perto da vítima?"
"Devia para a vítima?"
"Já trabalhou com a vítima?"
O programa deve no final emitir uma classificação sobre a participação da pessoa no crime. Se a pessoa responder positivamente a 2 questões ela deve ser classificada como "Suspeita", entre 3 e 4 como "Cúmplice" e 5 como "Assassino". Caso contrário, ele será classificado como "Inocente".
</pre>
"""

suspeito = 0

#validando respostas
p1 = str(input("Telefonou para a vítima? [sim/não]: "))
if p1.upper() == 'SIM':
  suspeito += 1
elif p1.upper() != 'SIM' and p1.upper() != 'NÃO':
  print("Resposta Invalida")

p2 = str(input("Esteve no local do crime? [sim/não]: "))
if p2.upper() == 'SIM':
  suspeito += 1
elif p2.upper() != 'SIM' and p2.upper() != 'NÃO':
  print("Resposta Invalida")

p3 = str(input("Mora perto da vítima? [sim/não]: "))
if p3.upper() == 'SIM':
  suspeito += 1
elif p3.upper() != 'SIM' and p3.upper() != 'NÃO':
  print("Resposta Invalida")

p4 = str(input("Devia para a vítima? [sim/não]: "))
if p4.upper() == 'SIM':
  suspeito += 1
elif p4.upper() != 'SIM' and p4.upper() != 'NÃO':
  print("Resposta Invalida")

p5 = str(input("Já trabalho com a vítima? [sim/não]: "))
if p5.upper() == 'SIM':
  suspeito += 1
elif p5.upper() != 'SIM' and p5.upper() != 'NÃO':
  print("Resposta Invalida")

#condições para classificar a pessoa
if suspeito < 2:
  print("Você é Inocente!")

elif suspeito == 2:
  print("Você é Suspeito!")

elif suspeito > 2 and suspeito <= 4:
  print("Você é um cúmplice!")

else:
  print("Você é o assasino!")

"""#### 20. Um posto está vendendo combustíveis com a seguinte tabela de descontos:
<pre>
Álcool:
até 20 litros, desconto de 3% por litro
acima de 20 litros, desconto de 5% por litro
Gasolina:
até 20 litros, desconto de 4% por litro
acima de 20 litros, desconto de 6% por litro

Escreva um algoritmo que leia o número de litros vendidos, o tipo de combustível (codificado da seguinte forma: A-álcool, G-gasolina), calcule e imprima o valor a ser pago pelo cliente sabendo-se que o preço do litro da gasolina é R$ 2,50 o preço do litro do álcool é R$ 1,90.
</pre>
"""

combustivel = str(input("[G - Gasolina / A - Alcool]\nQual o Combustível desejado?"))
if combustivel.upper() != 'G' and combustivel.upper() != 'A':
  print("Opção de combustivel invalida!")

litros = float(input("Quantos litros serão abastecidos? "))
if litros <= 0:
  print("A quantidade de combustivel não pode ser igual ou menor que zero")

if combustivel == 'G':
  if litros <= 20:
    valor = (litros * (2.50 - ((2.50 * 3) / 100)))
    print("O total a ser pago é R$ {}".format(valor))

  else:
    valor = (litros * (2.50 - ((2.50 * 5) / 100)))
    print("O total a ser pago é R$ {}".format(valor))

elif combustivel == 'A':
  if litros <= 20:
    valor = (litros * (1.90 - ((1.90 * 4) / 100)))
    print("O total a ser pago é R$ {}".format(valor))

  else:
    valor = (litros * (1.90 - ((1.90 * 6) / 100)))
    print("O total a ser pago é R$ {}".format(valor))

"""#### 21. Uma fruteira está vendendo frutas com a seguinte tabela de preços:
<pre>
                      Até 5 Kg           Acima de 5 Kg
Morango         R$ 2,50 por Kg          R$ 2,20 por Kg
Maçã            R$ 1,80 por Kg          R$ 1,50 por Kg
Se o cliente comprar mais de 8 Kg em frutas ou o valor total da compra ultrapassar R$ 25,00, receberá ainda um desconto de 10% sobre este total. Escreva um algoritmo para ler a quantidade (em Kg) de morangos e a quantidade (em Kg) de maças adquiridas e escreva o valor a ser pago pelo cliente.
</pre>
"""

morango = str(input("Você deseja morango? [Sim/Não]: "))

if morango.upper() == 'SIM':
  pesoMorango = float(input("Quantos Kg de morango você deseja? "))

  if pesoMorango > 0 and pesoMorango <= 5:
    valorMorango = pesoMorango * 2.5

  elif pesoMorango > 5:
    valorMorango = pesoMorango * 2.2

  else:
    print("O Peso não pode ser igual ou menor que Zero!")

elif morango.upper() == 'NÃO':
  pesoMorango = 0
  valorMorango = 0

else:
  print("Resposta Invalida!")

maca = str(input("Você deseja maça? [Sim/Não]: "))

if maca.upper() == 'SIM':
  pesoMaca = float(input("Quantos Kg de maça você deseja? "))

  if pesoMaca > 0 and pesoMaca <= 5:
    valorMaca = pesoMaca * 1.8

  elif pesoMaca > 5:
    valorMaca = pesoMaca * 1.5

  else:
    print("O Peso não pode ser igual ou menor que Zero!")

elif maca.upper() == 'NÃO':
  pesoMaca = 0
  valorMaca = 0

else:
  print("Resposta Invalida!")

if pesoMorango + pesoMaca > 8 or valorMorango + valorMaca > 25:
  total = valorMorango + valorMaca
  total = total - ((total * 10) / 100)
  print("O Valor total a ser pago é de R$ {}".format(total))

else:
  total = valorMorango + valorMaca
  print("O Valor total a ser pago é de R$ {}".format(total))

"""#### 22. O Hipermercado Tabajara está com uma promoção de carnes que é imperdível. Confira:
<pre>
                      Até 5 Kg           Acima de 5 Kg
File Duplo      R$ 4,90 por Kg          R$ 5,80 por Kg
Alcatra         R$ 5,90 por Kg          R$ 6,80 por Kg
Picanha         R$ 6,90 por Kg          R$ 7,80 por Kg
Para atender a todos os clientes, cada cliente poderá levar apenas um dos tipos de carne da promoção, porém não há limites para a quantidade de carne por cliente. Se compra for feita no cartão Tabajara o cliente receberá ainda um desconto de 5% sobre o total da compra. Escreva um programa que peça o tipo e a quantidade de carne comprada pelo usuário e gere um cupom fiscal, contendo as informações da compra: tipo e quantidade de carne, preço total, tipo de pagamento, valor do desconto e valor a pagar.
</pre>
"""

print("Opções de carne disponiveis:\n1 - File Duplo\n2 - Alcatra\n3 - Picanha")
carne = int(input("Qual o número da Carne desejada? "))

if carne == 1:
  tipo = 'File Duplo'
  peso = float(input("Quantos quilos de File Duplo você deseja? "))
  if peso > 0 and peso <= 5:
    total = peso * 4.9

  elif peso > 5:
    total = peso * 5.8

  else:
    print("A quantidade de carne não pode ser igual ou menor que Zero!")

elif carne == 2:
  tipo = 'Alcatra'
  peso = float(input("Quantos quilos de Alcatra você deseja? "))
  if peso > 0 and peso <= 5:
    total = peso * 5.9

  elif peso > 5:
    total = peso * 6.8

  else:
    print("A quantidade de carne não pode ser igual ou menor que Zero!")

elif carne == 3:
  tipo = 'Picanha'
  peso = float(input("Quantos quilos de Picanha você deseja? "))
  if peso > 0 and peso <= 5:
    total = peso * 6.9

  elif peso > 5:
    total = peso * 7.8

  else:
    print("A quantidade de carne não pode ser igual ou menor que Zero!")

else:
  print("Opção invalida, tente novamente!")

pagamento = str(input("\n[Dinheiro/Cartão]\nQual o metodo de pagamento? "))

if pagamento.upper() == 'DINHEIRO':
  print("\nCUPOM FISCAL\nProduto: {}\nQuantidade {} Kg\nPagamento: Dinheiro\nTotal: R$ {}".format(tipo, peso, total))

elif pagamento.upper() == 'CARTÃO':
  print("\nCUPOM FISCAL\nProduto: {}\nQuantidade {} Kg\nPagamento: Cartão\nDesconto: R$ {}\nTotal: R$ {}".format(tipo, peso, ((total * 5) / 100), total - ((total * 5) / 100)))

"""#### 23. Faça um Programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 6 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R\\$ 80,00 ou em galões de 3,6 litros, que custam R\\$ 25,00."""

area = float(input('Informe o tamanho da área a ser pintada em m²: '))
litros_tinta = area / 6

"""##### Informe ao usuário as quantidades de tinta a serem compradas e os respectivos preços em 3 situações.

Dica: lembre dos operadores // e % mostrados em exercícios anteriores<br>
Dica1: numero // 10 vai te dar como resposta a parte inteira da divisão do número por 10.<br>
Dica2: numero % 10 vai te dar o resto da divisão do número por 10.

##### 1. Comprar apenas latas de 18 litros: (apenas latas inteiras)
"""

import math

qtd_latas = math.ceil(litros_tinta / 18)
custo_latas = qtd_latas * 80
print("Somente latas de 18L:")
print(f'O cliente precisa comprar {qtd_latas} latas, que custarão R${custo_latas}.')

"""##### 2. Comprar apenas galões de 3,6 litros: (apenas galoes inteiros)"""

qtd_galoes = math.ceil(litros_tinta / 3.6)
custo_galoes = qtd_galoes * 25
print("Somente galões de 3.6L:")
print(f'O cliente precisa comprar {qtd_galoes} galões, que custarão R${custo_galoes}.')

"""##### 3. Misturar latas e galões, de forma que o desperdício de tinta seja menor. Acrescente 10% de folga e sempre arredonde os valores para cima, isto é, considere latas cheias.

O custo da lata é 80/18 = 4,44 R\\$/L

O custo do galão é 25/3,6 = 6,94 R\\$/L

A lata é mais econômica, então todas as latas inteiras que pudermos usar devemos comprar em latas. Se ficar faltando alguma coisa para completar devemos avaliar se é melhor comprar latas ou galões. Exemplo:

Se queremos comprar 90 litros. 5 latas dão exatamente 90 litros. Então devemos comprar tudo em latas.

Se queremos comprar 95 litros. 5 latas dão exatamente 90 litros. Então devemos comprar pelo menos 5 latas e avaliar o que falta, se estes últimos 5 litros valem mais apenas em latas ou galões.

Para os 5 litros faltantes precisamos de 2 galões que custam 50 reais no total. Ou de uma lata que custa 80 reais no total. Portanto, neste caso vale mais a pena usar 2 galões.

Se queremos comprar 107 litros. 5 latas dão exatamente 90 litros. Então devemos comprar pelo menos 5 latas e avaliar o que falta, se estes últimos 5 litros valem mais apenas em latas ou galões.

Para os 17 litros faltantes precisamos de 5 galões que custam 125 reais no total. Ou de uma lata que custa 80 reais no total. Portanto, neste caso vale mais a pena usar uma lata.

3 galões custam 75 reais, 4 galões custam 100 reais. Então, se for possível completar com até 3 galões escolhe-se galões. Qualquer quantidade maior que 3 galões, usa-se latas.

Podemos ir ao exercício:
"""

litros_necessarios_folga = litros_tinta * 1.1
qtd_latas_c = litros_necessarios_folga // 18

litros_necessarios_folga_faltando = litros_necessarios_folga - (qtd_latas_c * 18)
qtd_galoes_c = math.ceil(litros_necessarios_folga_faltando / 3.6)

custo_mix = (qtd_latas_c * 80) + (qtd_galoes_c * 25)

print("Mix de latas e galões:")
print(f'O cliente precisa comprar {qtd_latas_c} latas e {qtd_galoes_c} galões, que custarão {custo_mix}')